FROM node:18-alpine

RUN apk add --no-cache chromium
ENV CHROME_BIN=/usr/bin/chromium-browser

WORKDIR /app

COPY package*.json .
RUN npm install

COPY . .

CMD ["npm", "run", "test", "--", "--watch=false", "--browsers=ChromeHeadless", "--no-progress"]
