FROM maven:3.9.9-eclipse-temurin-17
WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src

ENV SPRING_PROFILES_ACTIVE=test
ENV LOGGING_LEVEL_ROOT=INFO

CMD ["mvn", "test", "-B"]
